name: Customer API CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Backend/src/CustomerService/**'
      - 'Backend/tests/CustomerService.Test/**' # ğŸ‘ˆ ThÃªm: Láº¯ng nghe thay Ä‘á»•i folder test
      - 'Backend/Shared.Tests/**'         # ğŸ‘ˆ ThÃªm: Láº¯ng nghe thay Ä‘á»•i folder Shared
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- BÆ¯á»šC 1: CÃ i Ä‘áº·t mÃ´i trÆ°á»ng .NET ---
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # --- BÆ¯á»šC 2: Cháº¡y Unit Test ---
      - name: Run Unit Tests
        run: |
          cd Backend
          dotnet test tests/CustomerService.Test/CustomerService.Test.csproj --verbosity normal

      # --- BÆ¯á»šC 3: Náº¿u Test Xanh (Pass) thÃ¬ má»›i Build Docker ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/src/CustomerService/Api/Dockerfile
          push: true
          tags: huyngoinfo/energy-customer-api:latest